spring.application.name=event-driven-hockey-analytics

spring.datasource.url=jdbc:postgresql://localhost:5432/hockey_db
spring.datasource.username=hockey
spring.datasource.password=hockey

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

logging.level.liquibase=DEBUG
logging.level.org.springframework.boot.autoconfigure.liquibase=DEBUG